### PR TITLE
Calculate prices into main.

### PR DESCRIPTION
**Pull request by mirakst**
This resolves issue #7 and adds the ability to use an array of sorted prices in the main program.

### CODE REVIEW

**Review by KasperHenningsen — APPROVED** [review]
Fuck det er lort! gg ez

**Review by KasperHenningsen — APPROVED** [review]
ad

**Review by KasperHenningsen — APPROVED** [review]

**Review by damniko — COMMENTED** [review]
wow.

**Review by damniko — APPROVED** [review]
nice

**Pull request merged**
